include instructions for dev testing
openstax/setup-openstax-machine pull request #6
Opened 2018-03-21 17:36 UTC by philschatz

This adds instructions for testing a Pull Request

2018-03-21 17:47 UTC, kerwinso requested changes

2018-03-21 17:47 UTC, kerwinso commented on README.md
> +bash <(curl -s https://raw.githubusercontent.com/openstax/setup-openstax-machine/master/${BRANCH_NAME}/setup.sh)
Shouldn't the `master/` be removed from this line?

2018-03-21 17:49 UTC, kerwinso commented on README.md
> +bash <(curl -s https://raw.githubusercontent.com/openstax/setup-openstax-machine/master/${BRANCH_NAME}/setup.sh)
Oh and add the `/bin/`:

2018-03-21 17:58 UTC, kerwinso approved these changes

2018-03-21 18:46 UTC, kerwinso reviewed
how do I unapprove changes? Need to consider which branch the ansible playbook is running from.

2018-03-21 18:49 UTC, philschatz commented
Ah, ansible clones the repository and uses the `master` branch. So it seems like the instructions would need to be updated to something like `BRANCH_NAME=foo bash <(curl -s https://raw.githubusercontent.com/openstax/setup-openstax-machine/${BRANCH_NAME}/bin/setup.sh)` and then maybe somehow change the `git clone` part of `setup.sh` to use `BRANCH_NAME` if it is available...


Also, @kerwinso you can click `[Reviewers]` and then select yourself, and then click `Files Changed`, and then `Reject`.

2018-03-21 18:53 UTC, m1yag1 commented
Hmm, I'm still wondering if this will be effective or not. No matter what the master branch is cloned down for the playbook. We would need to add a step that it is cloned down and then the proper branch is checked out. You can refer to this: https://github.com/openstax/setup-openstax-machine/blob/master/bin/setup.sh#L10-L12

2018-03-21 18:54 UTC, kerwinso requested changes
ah that feels good :P

2018-03-21 19:11 UTC, philschatz commented
ok, the conclusion is to add a list of dev instructions in order to keep less branching code in the actual install script

2018-03-21 19:16 UTC, kerwinso commented
Here's the README I'm testing against: https://github.com/openstax/setup-openstax-machine/tree/atom-plugins

I think the only step missing from the above file is to checkout the test branch (before installing dependencies).

2018-03-21 20:35 UTC, m1yag1 commented
Phil you may want to rebase off of master as there has been updates ;)

2018-03-29 17:41 UTC, m1yag1 approved these changes

2018-04-10 17:28 UTC, kerwinso approved these changes

2018-04-10 17:33 UTC, philschatz commented
Everyone approved 🎉  @m1yag1 can this be merged?

2018-04-10 17:35 UTC, merged